// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZPXPhYg-KkQGtm6__GCpgF7O8tIaLNs8',
    appId: '1:633807744190:web:f0be328ff2f5bb800382ef',
    messagingSenderId: '633807744190',
    projectId: 'mona-public-chat',
    authDomain: 'mona-public-chat.firebaseapp.com',
    storageBucket: 'mona-public-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9UFIoKXc4XfoXgs7cvBd9x2lE4HVmkwg',
    appId: '1:633807744190:android:a71b14fe48d3d9ae0382ef',
    messagingSenderId: '633807744190',
    projectId: 'mona-public-chat',
    storageBucket: 'mona-public-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXARdq7FVklz1ztbYIygOW0NzBex0a72o',
    appId: '1:633807744190:ios:63d57be63bc986fc0382ef',
    messagingSenderId: '633807744190',
    projectId: 'mona-public-chat',
    storageBucket: 'mona-public-chat.appspot.com',
    iosClientId: '633807744190-8j7gevh5038k4j7vrpd51q1071upltf7.apps.googleusercontent.com',
    iosBundleId: 'eu.monaproject.mona',
  );
}
